import React,{useMemo,useState}from'react';
import{Check,ChevronDown,Edit3,Loader2,Plus,Trash2,X}from'lucide-react';
import{supabase}from'@/lib/supabase';
import{Button}from'@/components/ui/button';
import{Input}from'@/components/ui/input';
import{calculateBusinessShare,calculateEquipmentMonthlyCost,calculateMaterialDisplayUnitCost,calculateMonthlyEquivalent,estimateSharedExpenseUse,materialDisplayUnit}from'@/lib/costEngine';

const INPUT='h-11 rounded-xl bg-background';
const FREQUENCIES=[['monthly','Mensual'],['weekly','Semanal'],['biweekly','Quincenal'],['quarterly','Trimestral'],['semiannual','Semestral'],['annual','Anual'],['one_time','Pago único']];
const SUBSCRIPTION_FREQUENCIES=FREQUENCIES.filter(([id])=>['monthly','quarterly','semiannual','annual'].includes(id));
const EXPENSE_CATEGORIES=[['operacion','Operación'],['software','Software y herramientas'],['administracion','Administración'],['marketing','Marketing'],['equipos','Equipos'],['otro','Otro']];
const UNITS=['unidad','hoja','pagina','paquete','caja','libra','onza','kilogramo','gramo','litro','mililitro','galon','metro','centimetro','pie','pulgada','yarda','docena','hora','minuto','otro'];
const MATERIAL_METHODS=[['exact','Cantidad exacta'],['yield','Rendimiento aproximado'],['estimated_use','Costo estimado por uso']];

function money(value){const n=Number(value||0);return new Intl.NumberFormat('es-DO',{style:'currency',currency:'DOP',maximumFractionDigits:2}).format(Number.isFinite(n)?n:0)}
function Select({value,onChange,children,disabled=false}){return <div className="relative"><select value={value} onChange={onChange} disabled={disabled} className="h-11 w-full appearance-none rounded-xl border border-input bg-background px-3 pr-9 text-sm text-foreground disabled:opacity-60">{children}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/></div>}
function Field({label,children,hint}){return <label className="space-y-1.5 text-sm font-semibold text-foreground"><span>{label}</span>{children}{hint&&<span className="block text-xs font-normal text-muted-foreground">{hint}</span>}</label>}

function ResourceShell({title,subtitle,suggestions,onSuggestion,onAdd,children,empty=false}){
 return <div className="space-y-5">
  <div><h2 className="text-2xl font-bold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{subtitle}</p></div>
  {suggestions?.length>0&&<div><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Sugerencias para tu negocio</p><div className="flex flex-wrap gap-2">{suggestions.map(item=><button key={item} type="button" onClick={()=>onSuggestion(item)} className="rounded-full border border-border bg-background px-3 py-2 text-sm text-foreground transition hover:border-primary hover:text-primary">+ {item}</button>)}</div></div>}
  <Button type="button" variant="outline" onClick={onAdd}><Plus className="mr-2 h-4 w-4"/>Agregar otro</Button>
  {children}
  {empty&&<p className="rounded-xl border border-dashed border-border p-4 text-center text-sm text-muted-foreground">Todavía no has agregado ninguno.</p>}
 </div>
}

function RowActions({onEdit,onDelete,disabled}){return <div className="flex shrink-0 gap-1"><button type="button" onClick={onEdit} disabled={disabled} className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-foreground disabled:opacity-50" aria-label="Editar"><Edit3 className="h-4 w-4"/></button><button type="button" onClick={onDelete} disabled={disabled} className="rounded-lg p-2 text-muted-foreground hover:bg-destructive/10 hover:text-destructive disabled:opacity-50" aria-label="Eliminar"><Trash2 className="h-4 w-4"/></button></div>}

function FormCard({title,onCancel,onSave,saving,children}){
 return <div className="rounded-2xl border border-primary/25 bg-primary/5 p-4 sm:p-5">
  <div className="mb-4 flex items-center justify-between gap-3"><p className="font-semibold">{title}</p><button type="button" onClick={onCancel} className="rounded-lg p-1.5 text-muted-foreground hover:bg-background"><X className="h-4 w-4"/></button></div>
  <div className="space-y-4">{children}</div>
  <div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onCancel}>Cancelar</Button><Button type="button" onClick={onSave} disabled={saving}>{saving?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Check className="mr-2 h-4 w-4"/>}Guardar</Button></div>
 </div>
}

export function ExpenseStep({suggestions=[],rows,setRows,workspaceId,user,onError,mode='expenses',businessConfig={}}){
 const subscriptionMode=mode==='subscriptions';
 const visibleRows=rows.filter(row=>subscriptionMode?row.is_subscription:!row.is_subscription);
 const blank={name:'',category:subscriptionMode?'software':'operacion',amount:'',frequency:'monthly',usage_scope:'business',business_use_pct:100,business_use_source:'default',guided_answers:{serviceUse:'half',usesProductionEquipment:false,usesCooling:false,highElectricalIntensity:false,highWaterUse:false,spaceUse:'small'},is_subscription:subscriptionMode};
 const[form,setForm]=useState(null);const[saving,setSaving]=useState(false);
 const frequencies=form?.is_subscription?SUBSCRIPTION_FREQUENCIES:FREQUENCIES;
 const open=(name='')=>setForm({...blank,name});
 const edit=row=>setForm({...blank,...row,amount:row.amount??'',business_use_pct:row.business_use_pct??(row.usage_scope==='personal'?0:row.usage_scope==='shared'?50:100),guided_answers:{...blank.guided_answers,...(row.metadata?.guided_answers||{})}});
 const save=async()=>{if(!form?.name?.trim()){onError?.('Escribe el nombre del gasto.');return}if(form.amount===''||Number(form.amount)<0){onError?.('Indica un monto aproximado válido.');return}setSaving(true);onError?.('');
  try{const pct=form.usage_scope==='business'?100:form.usage_scope==='personal'?0:Number(form.business_use_pct??50);const payload={workspace_id:workspaceId,user_id:user.id,created_by:(user.email||'').toLowerCase(),name:form.name.trim(),category:form.category,amount:Number(form.amount),frequency:form.frequency,usage_scope:form.usage_scope,business_use_pct:pct,business_use_source:form.usage_scope==='shared'?(form.business_use_source||'guided'):'default',is_subscription:Boolean(form.is_subscription),source:form.source||'onboarding',metadata:{...(form.metadata||{}),guided_answers:form.guided_answers||{},business_use_estimate_reason:form.business_use_estimate_reason||null}};
   const q=form.id?supabase.from('business_expenses').update(payload).eq('id',form.id).eq('workspace_id',workspaceId):supabase.from('business_expenses').insert(payload);
   const{data,error}=await q.select('*').single();if(error)throw error;
   setRows(list=>form.id?list.map(x=>x.id===data.id?data:x):[...list,data]);setForm(null);
  }catch(e){onError?.(e?.message||'No pudimos guardar el gasto.')}finally{setSaving(false)}};
 const remove=async row=>{const{error}=await supabase.from('business_expenses').delete().eq('id',row.id).eq('workspace_id',workspaceId);if(error){onError?.(error.message);return}setRows(list=>list.filter(x=>x.id!==row.id))};
 return <ResourceShell title={subscriptionMode?'Suscripciones y software':'Gastos del negocio'} subtitle={subscriptionMode?'Registra pagos recurrentes como Canva, ChatGPT, Adobe, hosting o CRM. CEO Rentable hará el prorrateo mensual después.':'Registra lo que pagas para operar. Marca lo compartido con tu hogar para no cargarle el 100% al negocio.'} suggestions={suggestions} onSuggestion={open} onAdd={()=>open()} empty={!visibleRows.length&&!form}>
  {form&&<FormCard title={form.id?'Editar gasto':'Nuevo gasto'} onCancel={()=>setForm(null)} onSave={save} saving={saving}>
   <div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre"><Input className={INPUT} value={form.name} onChange={e=>setForm(p=>({...p,name:e.target.value}))} placeholder="Ej. Electricidad"/></Field><Field label="Monto aproximado"><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">RD$</span><Input className={`${INPUT} pl-12`} type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm(p=>({...p,amount:e.target.value}))}/></div></Field></div>
   <div className="grid gap-4 sm:grid-cols-2"><Field label="Categoría"><Select value={form.category} onChange={e=>setForm(p=>({...p,category:e.target.value}))}>{EXPENSE_CATEGORIES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></Field><Field label="Frecuencia"><Select value={form.frequency} onChange={e=>setForm(p=>({...p,frequency:e.target.value}))}>{frequencies.map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></Field></div>
   <Field label="Uso"><Select value={form.usage_scope} onChange={e=>{const usage=e.target.value;setForm(p=>({...p,usage_scope:usage,business_use_pct:usage==='business'?100:usage==='personal'?0:(p.business_use_pct===100?50:p.business_use_pct),business_use_source:usage==='shared'?'guided':'default'}))}}><option value="business">100% negocio</option><option value="shared">Compartido hogar / negocio</option><option value="personal">Personal / no incluir</option></Select></Field>
   {form.usage_scope==='shared'&&<SharedUseAssistant form={form} setForm={setForm} businessConfig={businessConfig}/>} 
   {form.amount!==''&&form.frequency!=='one_time'&&<div className="rounded-xl border border-primary/20 bg-background p-3 text-sm"><p className="text-muted-foreground">CEO Rentable lo convierte automáticamente a mensual:</p><p className="mt-1 font-bold text-primary">{money(calculateBusinessShare(calculateMonthlyEquivalent(Number(form.amount||0),form.frequency),form.usage_scope==='business'?100:form.usage_scope==='personal'?0:Number(form.business_use_pct||0)))} al mes para el negocio</p></div>}
   {!subscriptionMode&&<label className="flex items-start gap-3 rounded-xl border border-border bg-background p-3 text-sm"><input type="checkbox" className="mt-0.5 h-4 w-4" checked={form.is_subscription} onChange={e=>setForm(p=>({...p,is_subscription:e.target.checked,frequency:e.target.checked&&!['monthly','quarterly','semiannual','annual'].includes(p.frequency)?'monthly':p.frequency,category:e.target.checked&&p.category==='operacion'?'software':p.category}))}/><span><strong>Es una suscripción o software recurrente</strong><span className="mt-0.5 block text-xs text-muted-foreground">Si lo marcas, aparecerá en la sección Suscripciones.</span></span></label>}
  </FormCard>}
  <div className="space-y-2">{visibleRows.map(row=><div key={row.id} className="flex items-center justify-between gap-3 rounded-xl border border-border bg-background p-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-semibold">{row.name}</p>{row.is_subscription&&<span className="rounded-full bg-primary/10 px-2 py-0.5 text-[11px] font-semibold text-primary">Suscripción</span>}</div><p className="text-xs text-muted-foreground">{money(row.amount)} · {FREQUENCIES.find(f=>f[0]===row.frequency)?.[1]||row.frequency} · {row.usage_scope==='shared'?(`${row.business_use_pct??50}% negocio`):row.usage_scope==='personal'?'No incluir':'Negocio'}{row.frequency!=='one_time'?` · ${money(calculateBusinessShare(calculateMonthlyEquivalent(row.amount,row.frequency),row.usage_scope==='business'?100:row.usage_scope==='personal'?0:Number(row.business_use_pct??50)))} / mes`:''}</p></div><RowActions onEdit={()=>edit(row)} onDelete={()=>remove(row)} disabled={saving}/></div>)}</div>
 </ResourceShell>
}

function SharedUseAssistant({form,setForm,businessConfig}){
 const normalized=(form.name||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
 const isElectric=normalized.includes('electric')||normalized.includes('luz')||normalized.includes('energia');
 const isService=normalized.includes('internet')||normalized.includes('telefono')||normalized.includes('celular');
 const isWater=normalized.includes('agua');
 const isRent=normalized.includes('alquiler')||normalized.includes('renta');
 const answers=form.guided_answers||{};
 const applyEstimate=(nextAnswers=answers)=>{
  const estimate=estimateSharedExpenseUse({
   expenseName:form.name,
   industryCodes:businessConfig?.industry_codes||[],
   workHoursPerDay:businessConfig?.work_hours_per_day||0,
   worksFromHome:(businessConfig?.workplace_modes||[]).includes('home')||(businessConfig?.workplace_modes||[]).includes('combined'),
   answers:nextAnswers,
  });
  setForm(p=>({...p,guided_answers:nextAnswers,business_use_pct:estimate.pct,business_use_source:'guided',business_use_estimate_reason:estimate.reason}));
 };
 return <div className="rounded-xl border border-border bg-background p-3">
  <p className="text-sm font-semibold">Te ayudamos a estimarlo</p>
  <p className="mt-1 text-xs text-muted-foreground">Responde con aproximaciones. La sugerencia queda editable.</p>
  {isService&&<div className="mt-3"><Field label="¿Cómo usas este servicio?"><Select value={answers.serviceUse||'half'} onChange={e=>{const next={...answers,serviceUse:e.target.value};applyEstimate(next)}}><option value="mainly_personal">Principalmente personal</option><option value="half">Mitad personal / mitad negocio</option><option value="mainly_business">Principalmente negocio</option><option value="business_only">100% negocio</option></Select></Field></div>}
  {isElectric&&<div className="mt-3 grid gap-2 sm:grid-cols-2">
   {[[ 'usesProductionEquipment','Uso equipos eléctricos para producir'],['usesCooling','Uso aire acondicionado durante el trabajo'],['highElectricalIntensity','Mi producción consume bastante electricidad']].map(([key,label])=><label key={key} className="flex items-start gap-2 rounded-lg border border-border p-2 text-xs"><input type="checkbox" className="mt-0.5" checked={Boolean(answers[key])} onChange={e=>{const next={...answers,[key]:e.target.checked};applyEstimate(next)}}/><span>{label}</span></label>)}
  </div>}
  {isWater&&<div className="mt-3"><label className="flex items-start gap-2 rounded-lg border border-border p-2 text-xs"><input type="checkbox" className="mt-0.5" checked={Boolean(answers.highWaterUse)} onChange={e=>{const next={...answers,highWaterUse:e.target.checked};applyEstimate(next)}}/><span>Uso agua frecuentemente como parte del servicio o producción</span></label></div>}
  {isRent&&<div className="mt-3"><Field label="¿Cuánto espacio del hogar usa el negocio?"><Select value={answers.spaceUse||'small'} onChange={e=>{const next={...answers,spaceUse:e.target.value};applyEstimate(next)}}><option value="small">Un espacio pequeño</option><option value="medium">Una habitación o área importante</option><option value="large">Gran parte de la vivienda</option><option value="dedicated">Espacio dedicado completamente al negocio</option></Select></Field></div>}
  {!isElectric&&!isService&&!isWater&&!isRent&&<div className="mt-3 grid gap-2 sm:grid-cols-4">{[[25,'Principalmente personal'],[50,'Mitad y mitad'],[75,'Principalmente negocio'],[100,'Solo negocio']].map(([pct,label])=><button key={pct} type="button" onClick={()=>setForm(p=>({...p,business_use_pct:pct,business_use_source:'guided',business_use_estimate_reason:'Estimación seleccionada por la usuaria según el nivel de uso empresarial.'}))} className={`rounded-xl border px-3 py-2 text-xs font-semibold transition ${Number(form.business_use_pct)===pct?'border-primary bg-primary/10 text-primary':'border-border hover:border-primary/40'}`}>{label}<span className="mt-1 block text-[11px] font-normal">{pct}%</span></button>)}</div>}
  {(isElectric||isService||isWater||isRent)&&<button type="button" onClick={()=>applyEstimate(answers)} className="mt-3 rounded-lg border border-primary/30 px-3 py-2 text-xs font-semibold text-primary">Calcular estimación sugerida</button>}
  <div className="mt-3 rounded-lg bg-primary/5 p-2"><p className="text-xs text-muted-foreground">Estimación sugerida</p><p className="font-bold text-primary">{Number(form.business_use_pct||0)}% para el negocio</p>{form.business_use_estimate_reason&&<p className="mt-1 text-[11px] text-muted-foreground">{form.business_use_estimate_reason}</p>}</div>
  <div className="mt-3"><Field label="Puedes modificarla"><Input className={INPUT} inputMode="decimal" type="number" min="0" max="100" step="1" value={form.business_use_pct} onChange={e=>setForm(p=>({...p,business_use_pct:e.target.value,business_use_source:'manual'}))}/></Field></div>
 </div>
}

export function MaterialStep({title='Materiales e insumos',subtitle,suggestions=[],rows,setRows,workspaceId,user,onError}){
 const blank={name:'',purchase_price:'',purchase_quantity:'',unit:'unidad',custom_unit:'',cost_method:'exact',yield_quantity:'',yield_unit:'pagina',estimated_cost_per_use:'',waste_pct:'',supplier:''};const[form,setForm]=useState(null);const[saving,setSaving]=useState(false);
 const open=(name='')=>setForm({...blank,name});const edit=row=>setForm({...blank,...row,purchase_price:row.purchase_price??'',purchase_quantity:row.purchase_quantity??'',yield_quantity:row.yield_quantity??'',estimated_cost_per_use:row.estimated_cost_per_use??'',waste_pct:row.waste_pct??'',supplier:row.supplier??''});
 const unitLabel=useMemo(()=>form?.unit==='otro'?(form?.custom_unit||'personalizada'):form?.unit,[form?.unit,form?.custom_unit]);
 const previewMaterial=useMemo(()=>form?{...form,purchase_price:Number(form.purchase_price||0),purchase_quantity:Number(form.purchase_quantity||0),yield_quantity:form.yield_quantity===''?null:Number(form.yield_quantity),estimated_cost_per_use:form.estimated_cost_per_use===''?null:Number(form.estimated_cost_per_use),waste_pct:Number(form.waste_pct||0)}:null,[form]);
 let previewCost=null;try{if(previewMaterial?.purchase_price>=0&&previewMaterial?.purchase_quantity>0){previewCost=calculateMaterialDisplayUnitCost(previewMaterial)}}catch{previewCost=null}
 const save=async()=>{if(!form?.name?.trim())return onError?.('Escribe el nombre del material.');if(Number(form.purchase_price)<0||form.purchase_price==='')return onError?.('Indica cuánto pagaste.');if(Number(form.purchase_quantity)<=0||form.purchase_quantity==='')return onError?.('Indica cuánta cantidad compraste.');if(form.unit==='otro'&&!form.custom_unit?.trim())return onError?.('Escribe la unidad personalizada.');if(form.cost_method==='yield'&&(form.yield_quantity===''||Number(form.yield_quantity)<=0))return onError?.('Indica aproximadamente cuántos usos o servicios rinde.');if(form.cost_method==='estimated_use'&&(form.estimated_cost_per_use===''||Number(form.estimated_cost_per_use)<0))return onError?.('Indica el costo estimado por uso.');if(Number(form.waste_pct||0)<0||Number(form.waste_pct||0)>=100)return onError?.('La merma debe estar entre 0% y menos de 100%.');setSaving(true);onError?.('');
  try{const payload={workspace_id:workspaceId,user_id:user.id,created_by:(user.email||'').toLowerCase(),name:form.name.trim(),purchase_price:Number(form.purchase_price),purchase_quantity:Number(form.purchase_quantity),unit:form.unit,custom_unit:form.unit==='otro'?form.custom_unit.trim():null,cost_method:form.cost_method||'exact',yield_quantity:form.cost_method==='yield'?Number(form.yield_quantity):null,yield_unit:form.cost_method==='yield'?(form.yield_unit||'uso'):null,estimated_cost_per_use:form.cost_method==='estimated_use'?Number(form.estimated_cost_per_use):null,waste_pct:Number(form.waste_pct||0),supplier:form.supplier?.trim()||null,source:form.source||'onboarding'};const q=form.id?supabase.from('business_materials').update(payload).eq('id',form.id).eq('workspace_id',workspaceId):supabase.from('business_materials').insert(payload);const{data,error}=await q.select('*').single();if(error)throw error;setRows(list=>form.id?list.map(x=>x.id===data.id?data:x):[...list,data]);setForm(null)}catch(e){onError?.(e?.message||'No pudimos guardar el material.')}finally{setSaving(false)}};
 const remove=async row=>{const{error}=await supabase.from('business_materials').delete().eq('id',row.id).eq('workspace_id',workspaceId);if(error)return onError?.(error.message);setRows(list=>list.filter(x=>x.id!==row.id))};
 return <ResourceShell title={title} subtitle={subtitle} suggestions={suggestions} onSuggestion={open} onAdd={()=>open()} empty={!rows.length&&!form}>
  {form&&<FormCard title={form.id?'Editar material':'Nuevo material'} onCancel={()=>setForm(null)} onSave={save} saving={saving}>
   <Field label="Material o insumo"><Input className={INPUT} value={form.name} onChange={e=>setForm(p=>({...p,name:e.target.value}))} placeholder="Ej. Papel bond"/></Field>
   <div className="grid gap-4 sm:grid-cols-2"><Field label="¿Cuánto pagaste?"><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">RD$</span><Input className={`${INPUT} pl-12`} inputMode="decimal" type="number" min="0" step="0.01" value={form.purchase_price} onChange={e=>setForm(p=>({...p,purchase_price:e.target.value}))}/></div></Field><Field label="¿Cuánta cantidad compraste?"><Input className={INPUT} inputMode="decimal" type="number" min="0.0001" step="0.0001" value={form.purchase_quantity} onChange={e=>setForm(p=>({...p,purchase_quantity:e.target.value}))}/></Field></div>
   <Field label="Unidad de compra"><Select value={form.unit} onChange={e=>setForm(p=>({...p,unit:e.target.value}))}>{UNITS.map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</Select></Field>
   {form.unit==='otro'&&<Field label="Unidad personalizada"><Input className={INPUT} value={form.custom_unit||''} onChange={e=>setForm(p=>({...p,custom_unit:e.target.value}))} placeholder="Ej. rollo, botella, plancha"/></Field>}
   <Field label="¿Cómo prefieres medir lo que consumes?" hint="Si es fácil medirlo, usa cantidad exacta. Si no, usa rendimiento o costo aproximado por uso."><Select value={form.cost_method} onChange={e=>setForm(p=>({...p,cost_method:e.target.value}))}>{MATERIAL_METHODS.map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></Field>
   {form.cost_method==='yield'&&<div className="grid gap-4 sm:grid-cols-2"><Field label="¿Aproximadamente cuánto rinde?"><Input className={INPUT} inputMode="decimal" type="number" min="0.0001" step="0.0001" value={form.yield_quantity} onChange={e=>setForm(p=>({...p,yield_quantity:e.target.value}))}/></Field><Field label="Rinde en"><Select value={form.yield_unit||'pagina'} onChange={e=>setForm(p=>({...p,yield_unit:e.target.value}))}>{UNITS.filter(x=>x!=='otro').map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</Select></Field></div>}
   {form.cost_method==='estimated_use'&&<Field label="Costo estimado por uso" hint="Úsalo solo cuando medir cantidad o rendimiento no sea práctico."><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">RD$</span><Input className={`${INPUT} pl-12`} inputMode="decimal" type="number" min="0" step="0.01" value={form.estimated_cost_per_use} onChange={e=>setForm(p=>({...p,estimated_cost_per_use:e.target.value}))}/></div></Field>}
   <div className="grid gap-4 sm:grid-cols-2"><Field label="Merma %" hint="Opcional. Déjalo en 0 si no deseas incluir desperdicio."><Input className={INPUT} inputMode="decimal" type="number" min="0" max="99.99" step="0.01" value={form.waste_pct} onChange={e=>setForm(p=>({...p,waste_pct:e.target.value}))}/></Field><Field label="Proveedor" hint="Opcional"><Input className={INPUT} value={form.supplier||''} onChange={e=>setForm(p=>({...p,supplier:e.target.value}))} placeholder="Ej. Distribuidora XYZ"/></Field></div>
   {previewCost!==null&&<div className="rounded-xl border border-primary/20 bg-background p-3 text-sm"><p className="text-muted-foreground">CEO Rentable calcula automáticamente:</p><p className="mt-1 text-lg font-bold text-primary">{money(previewCost)} por {materialDisplayUnit(previewMaterial)}</p><p className="mt-1 text-xs text-muted-foreground">Compra registrada: {money(form.purchase_price)} por {form.purchase_quantity} {unitLabel}. No tienes que calcular el costo unitario.</p></div>}
  </FormCard>}
  <div className="space-y-2">{rows.map(row=>{let unitCost=null;try{unitCost=calculateMaterialDisplayUnitCost(row)}catch{unitCost=null}return <div key={row.id} className="flex items-center justify-between gap-3 rounded-xl border border-border bg-background p-3"><div className="min-w-0"><p className="truncate font-semibold">{row.name}</p><p className="text-xs text-muted-foreground">{money(row.purchase_price)} · {row.purchase_quantity} {row.unit==='otro'?(row.custom_unit||'unidad'):row.unit}{unitCost!==null?` · ${money(unitCost)} por ${materialDisplayUnit(row)}`:''}</p></div><RowActions onEdit={()=>edit(row)} onDelete={()=>remove(row)} disabled={saving}/></div>})}</div>
 </ResourceShell>
}

export function EquipmentStep({suggestions=[],rows,setRows,workspaceId,user,onError}){
 const blank={name:'',estimated_price:'',purchased_on:'',usage_scope:'business',usage_intensity:'regular',business_use_pct:100,operational_life_months:36};const[form,setForm]=useState(null);const[saving,setSaving]=useState(false);
 const open=(name='')=>setForm({...blank,name});const edit=row=>setForm({...blank,...row,estimated_price:row.estimated_price??'',purchased_on:row.purchased_on||'',business_use_pct:row.business_use_pct??(row.usage_scope==='shared'?50:100),operational_life_months:row.operational_life_months??36});
 const save=async()=>{if(!form?.name?.trim())return onError?.('Escribe el nombre del equipo.');if(form.estimated_price===''||Number(form.estimated_price)<0)return onError?.('Indica un precio aproximado válido.');setSaving(true);onError?.('');
  try{const payload={workspace_id:workspaceId,user_id:user.id,created_by:(user.email||'').toLowerCase(),name:form.name.trim(),estimated_price:Number(form.estimated_price),purchased_on:form.purchased_on||null,usage_scope:form.usage_scope,usage_intensity:form.usage_intensity,business_use_pct:form.usage_scope==='shared'?Number(form.business_use_pct||50):100,operational_life_months:Number(form.operational_life_months||36),source:form.source||'onboarding'};const q=form.id?supabase.from('business_equipment').update(payload).eq('id',form.id).eq('workspace_id',workspaceId):supabase.from('business_equipment').insert(payload);const{data,error}=await q.select('*').single();if(error)throw error;setRows(list=>form.id?list.map(x=>x.id===data.id?data:x):[...list,data]);setForm(null)}catch(e){onError?.(e?.message||'No pudimos guardar el equipo.')}finally{setSaving(false)}};
 const remove=async row=>{const{error}=await supabase.from('business_equipment').delete().eq('id',row.id).eq('workspace_id',workspaceId);if(error)return onError?.(error.message);setRows(list=>list.filter(x=>x.id!==row.id))};
 return <ResourceShell title="Equipos y herramientas" subtitle="No te pediremos depreciación ni vida útil. Solo el dato que conoces hoy; CEO Rentable hará la distribución después." suggestions={suggestions} onSuggestion={open} onAdd={()=>open()} empty={!rows.length&&!form}>
  {form&&<FormCard title={form.id?'Editar equipo':'Nuevo equipo'} onCancel={()=>setForm(null)} onSave={save} saving={saving}>
   <div className="grid gap-4 sm:grid-cols-2"><Field label="Equipo o herramienta"><Input className={INPUT} value={form.name} onChange={e=>setForm(p=>({...p,name:e.target.value}))} placeholder="Ej. Impresora"/></Field><Field label="Precio aproximado"><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">RD$</span><Input className={`${INPUT} pl-12`} type="number" min="0" step="0.01" value={form.estimated_price} onChange={e=>setForm(p=>({...p,estimated_price:e.target.value}))}/></div></Field></div>
   <Field label="Fecha aproximada de compra" hint="Opcional. Si no la recuerdas, déjala vacía."><Input className={INPUT} type="date" value={form.purchased_on||''} onChange={e=>setForm(p=>({...p,purchased_on:e.target.value}))}/></Field>
   <div className="grid gap-4 sm:grid-cols-2"><Field label="Uso"><Select value={form.usage_scope} onChange={e=>setForm(p=>({...p,usage_scope:e.target.value,business_use_pct:e.target.value==='shared'?(p.business_use_pct===100?50:p.business_use_pct):100}))}><option value="business">Exclusivo del negocio</option><option value="shared">Compartido</option></Select></Field><Field label="Frecuencia de uso"><Select value={form.usage_intensity} onChange={e=>setForm(p=>({...p,usage_intensity:e.target.value,operational_life_months:e.target.value==='high'?24:e.target.value==='low'?48:36}))}><option value="low">Poco</option><option value="regular">Regular</option><option value="high">Mucho</option></Select></Field></div>
   {form.usage_scope==='shared'&&<Field label="Uso empresarial estimado %"><Input className={INPUT} inputMode="decimal" type="number" min="0" max="100" step="1" value={form.business_use_pct} onChange={e=>setForm(p=>({...p,business_use_pct:e.target.value}))}/></Field>}
   <Field label="Duración operativa estimada" hint="CEO Rentable usa esto para repartir el desgaste del equipo; no es depreciación fiscal."><Select value={String(form.operational_life_months||36)} onChange={e=>setForm(p=>({...p,operational_life_months:Number(e.target.value)}))}><option value="24">2 años</option><option value="36">3 años</option><option value="48">4 años</option><option value="60">5 años</option></Select></Field>
   {form.estimated_price!==''&&Number(form.estimated_price)>=0&&<div className="rounded-xl border border-primary/20 bg-background p-3 text-sm"><p className="text-muted-foreground">Costo operativo estimado del equipo:</p><p className="mt-1 font-bold text-primary">{money(calculateEquipmentMonthlyCost({acquisitionCost:Number(form.estimated_price||0),usefulMonths:Number(form.operational_life_months||36),businessUsePct:form.usage_scope==='shared'?Number(form.business_use_pct||50):100,intensity:form.usage_intensity}))} / mes</p></div>}
  </FormCard>}
  <div className="space-y-2">{rows.map(row=><div key={row.id} className="flex items-center justify-between gap-3 rounded-xl border border-border bg-background p-3"><div className="min-w-0"><p className="truncate font-semibold">{row.name}</p><p className="text-xs text-muted-foreground">{money(row.estimated_price)} · {row.usage_scope==='shared'?(`${row.business_use_pct??50}% negocio`):'Negocio'} · uso {row.usage_intensity==='high'?'alto':row.usage_intensity==='low'?'bajo':'regular'} · {money(row.monthly_cost_override??calculateEquipmentMonthlyCost({acquisitionCost:row.estimated_price,usefulMonths:row.operational_life_months||36,businessUsePct:row.usage_scope==='shared'?Number(row.business_use_pct??50):100,intensity:row.usage_intensity}))}/mes</p></div><RowActions onEdit={()=>edit(row)} onDelete={()=>remove(row)} disabled={saving}/></div>)}</div>
 </ResourceShell>
}
